variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable region {}
variable subnet_avail_zone {}
variable env_prefix {}
variable ip_addresses_range {}
variable instance_type {}
variable image_name {}
variable configuration {}